"""create room_sessions table

Revision ID: fb09f7e59ba5
Revises: 
Create Date: 2026-06-05 11:31:48.875267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb09f7e59ba5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('intake_data', sa.JSON(), nullable=False),
    sa.Column('design_plan', sa.JSON(), nullable=True),
    sa.Column('plan_version', sa.Integer(), nullable=True),
    sa.Column('conversation_history', sa.JSON(), nullable=True),
    sa.Column('image_job_id', sa.String(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('image_status', sa.String(), nullable=True),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('session_state', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_sessions_id'), 'room_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_sessions_id'), table_name='room_sessions')
    op.drop_table('room_sessions')
    # ### end Alembic commands ###
